GET http://localhost:8000/member/member/count
Accept: application/json
token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYmYiOjE2OTIyNTg4MDEsIm1vYmlsZSI6IjE3NzYyMjczNTk2IiwiaWQiOjE2OTEzMDY2ODk2MzIwMTQzMzYsImV4cCI6MTY5MjI4NDAwMSwiaWF0IjoxNjkyMjU4ODAxfQ.hZxlLB16416tnPg6o_dmt9ZVCk90-HE3xG_4x-GcSuA

###

POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=13289806791
###

POST http://localhost:8000/member/member/send-code
Content-Type: application/json

{
  "mobile": "13289806788"
}

###
POST http://localhost:8000/member/member/login
Content-Type: application/json

{
  "mobile": "13289806788",
  "code":"8888"
}
###