server:
  port: 8000
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600
      routes:
        - id: member
          predicates:
            - Path=/member/**
          uri: lb://member
        - id: business
          predicates:
            - Path=/business/**
          uri: lb://business
        - id: batch
          predicates:
            - Path=/batch/**
          uri: lb://batch
