server:
  port: 8002
  servlet:
    context-path: /business
spring:
  application:
    name: business
  # 数据库连接
  datasource:
    url: jdbc:mysql://rm-cn-nwy3cdcr9000qk8o.rwlb.cn-chengdu.rds.aliyuncs.com/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_business
    password: Zhn789@@
    driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis xml路径
  devtools:
    livereload:
      port: 35728
logging:
    level:
      com.zhn.train.business.mapper:
        trace
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    local-cache-scope: statement


